blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/kwalenta/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Check out our development guide for technical information
  - name: 💬 GitHub Skills Course
    url: https://skills.github.com/
    about: Learn more about GitHub Skills courses